### ISSUE TITLE
Not able to load skybox texture

### ISSUE THREAD

**Issue by insominx** [The-Gamedev-Guru/Unity-Addressables-Level-2#1]
Unity (2019.2.4) complains that it can't read the skybox textures on both mac and windows.  Results in showing white images.

**Comment by rubentorresbonet** [comment]
Thanks for the report. I submitted a missing change.
I tested it on 2019.2.4f1 and it works; make sure your _Play Mode Script_ in the Addressables window is set to _Fast Mode_. Alternatively, build the player content.
Let me know if you still have issues.
